const DailyProgress = require('../models/DailyProgress');
const Streak = require('../models/Streak');
const Phase = require('../models/Phase');
const Week = require('../models/Week');
const Topic = require('../models/Topic');
const DailyTask = require('../models/DailyTask');
const DSAQuestion = require('../models/DSAQuestion');
const AptitudeTopic = require('../models/AptitudeTopic');
const DSATopic = require('../models/DSATopic');
const User = require('../models/User');

const ROADMAP_START_DATE = new Date('2026-06-15');

// Helper to get date string in YYYY-MM-DD
const getDateString = (dateObj = new Date()) => {
  const year = dateObj.getFullYear();
  const month = String(dateObj.getMonth() + 1).padStart(2, '0');
  const day = String(dateObj.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

// Helper to check if a date is yesterday
const isYesterday = (lastDateStr, todayDateStr) => {
  if (!lastDateStr) return false;
  const last = new Date(lastDateStr);
  const today = new Date(todayDateStr);
  const diffTime = Math.abs(today - last);
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return diffDays === 1;
};

// Auto-generation of 6 daily tasks
const autoGenerateDailyTasks = async (userId, dateStr) => {
  try {
    const existing = await DailyTask.find({ userId, date: dateStr });
    if (existing && existing.length > 0) {
      return existing;
    }

    // 1. Calculate recommended week based on ROADMAP_START_DATE
    const currentDate = new Date(dateStr);
    const diffTime = currentDate - ROADMAP_START_DATE;
    const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
    const recommendedWeek = Math.max(1, Math.floor(diffDays / 7) + 1);

    // 2. Fetch the corresponding Week
    const weekDoc = await Week.findOne({ userId, globalWeekNumber: recommendedWeek });
    let devSub = null;
    let ipSub = null;
    let weekId = null;

    if (weekDoc) {
      weekId = weekDoc._id;
      const topics = await Topic.find({ userId, weekId: weekDoc._id });
      
      // Find first incomplete subtopic for Dev/Tech Skill
      const devTopic = topics.find(t => t.category === 'Development');
      if (devTopic) {
        const sub = devTopic.subtopics.find(s => !s.isCompleted);
        if (sub) {
          devSub = { title: `Study Tech Skill: ${devTopic.name} - ${sub.name}`, subtopicId: sub._id };
        } else {
          devSub = { title: `Review Tech Skill: ${devTopic.name}`, subtopicId: null };
        }
      }

      // Find first incomplete subtopic for IP Skill
      const ipTopic = topics.find(t => t.category === 'IP Skills');
      if (ipTopic) {
        const sub = ipTopic.subtopics.find(s => !s.isCompleted);
        if (sub) {
          ipSub = { title: `Study IP Skill: ${ipTopic.name} - ${sub.name}`, subtopicId: sub._id };
        } else {
          ipSub = { title: `Review IP Skill: ${ipTopic.name}`, subtopicId: null };
        }
      }
    }

    // Find first incomplete subtopic for Aptitude
    const aptTopic = await AptitudeTopic.findOne({ userId, isCompleted: false }).sort({ createdAt: 1 });
    let aptTitle = 'Practice Aptitude questions';
    let aptSubtopicId = null;
    if (aptTopic) {
      const sub = aptTopic.subtopics.find(s => !s.isCompleted);
      if (sub) {
        aptTitle = `Practice Aptitude: ${aptTopic.topicName} - ${sub.name}`;
        aptSubtopicId = sub._id;
      }
    }

    // Find first incomplete DSA subtopic
    const firstIncompleteDSATopic = await DSATopic.findOne({ userId, isCompleted: false }).sort({ createdAt: 1 });
    let dsaTitle = 'Solve DSA coding questions';
    if (firstIncompleteDSATopic) {
      const sub = firstIncompleteDSATopic.subtopics.find(s => !s.isCompleted);
      if (sub) {
        dsaTitle = `Solve DSA: ${firstIncompleteDSATopic.topicName} - ${sub.name}`;
      } else {
        dsaTitle = `Solve DSA: ${firstIncompleteDSATopic.topicName}`;
      }
    }

    // Construct the 6 tasks
    const tasks = [
      {
        userId,
        date: dateStr,
        title: 'Log study hours target',
        category: 'Study Hours',
        completed: false,
        estimatedMinutes: 240,
        generatedByRoadmap: true
      },
      {
        userId,
        date: dateStr,
        title: dsaTitle,
        category: 'DSA',
        completed: false,
        estimatedMinutes: 90,
        generatedByRoadmap: true
      },
      {
        userId,
        date: dateStr,
        title: aptTitle,
        category: 'Aptitude',
        completed: false,
        estimatedMinutes: 60,
        subtopicId: aptSubtopicId,
        generatedByRoadmap: true
      },
      {
        userId,
        date: dateStr,
        title: ipSub ? ipSub.title : 'Study IP Skill concepts',
        category: 'IP Skill',
        completed: false,
        estimatedMinutes: 45,
        weekId,
        subtopicId: ipSub ? ipSub.subtopicId : null,
        generatedByRoadmap: true
      },
      {
        userId,
        date: dateStr,
        title: devSub ? devSub.title : 'Study Technical Skill modules',
        category: 'Technical Skill',
        completed: false,
        estimatedMinutes: 120,
        weekId,
        subtopicId: devSub ? devSub.subtopicId : null,
        generatedByRoadmap: true
      },
      {
        userId,
        date: dateStr,
        title: '15 Minute Speaking Practice',
        category: 'English Speaking',
        completed: false,
        estimatedMinutes: 15,
        generatedByRoadmap: true
      }
    ];

    return await DailyTask.insertMany(tasks);
  } catch (error) {
    console.error('Failed to auto-generate tasks:', error);
    return [];
  }
};

// @desc    Get today's daily tasks & habits checklist
// @route   GET /api/daily/today
// @access  Private
exports.getTodayChecklist = async (req, res, next) => {
  try {
    const dateStr = getDateString();
    
    // Auto generate daily tasks
    const tasks = await autoGenerateDailyTasks(req.user.id, dateStr);

    // Fetch or create DailyProgress summary record
    let progress = await DailyProgress.findOne({ userId: req.user.id, date: dateStr });
    if (!progress) {
      progress = await DailyProgress.create({
        userId: req.user.id,
        date: dateStr,
        studyHoursTarget: 4,
        dsaTarget: 4,
        completionPercentage: 0,
        wentToCollege: false,
        isHoliday: false
      });
    }

    // Calculate score
    const weights = {
      'Study Hours': 15,
      'DSA': 20,
      'Aptitude': 20,
      'IP Skill': 20,
      'Technical Skill': 15,
      'English Speaking': 10
    };
    let completion = 0;
    tasks.forEach(t => {
      if (t.completed) {
        completion += weights[t.category] || 0;
      }
    });

    if (progress.isHoliday) {
      completion = 100;
    }

    if (progress.completionPercentage !== completion) {
      progress.completionPercentage = completion;
      await progress.save();
    }

    // Fetch streak
    let streakObj = await Streak.findOne({ userId: req.user.id });
    if (!streakObj) {
      streakObj = await Streak.create({ userId: req.user.id });
    }

    res.status(200).json({
      success: true,
      tasks,
      progress,
      streak: streakObj
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Toggle dynamic DailyTask item, syncing to roadmap & updating daily score
// @route   POST /api/daily/tasks/:id/toggle
// @access  Private
exports.toggleDailyTaskItem = async (req, res, next) => {
  try {
    const taskId = req.params.id;
    const task = await DailyTask.findOne({ _id: taskId, userId: req.user.id });
    if (!task) {
      return res.status(404).json({
        success: false,
        message: 'Daily task not found'
      });
    }

    // Toggle status
    task.completed = !task.completed;
    await task.save();

    // Two-way sync to the Roadmap Topics
    if (task.subtopicId) {
      if (['Technical Skill', 'IP Skill'].includes(task.category) && task.weekId) {
        // Dev or IP Skill
        const topic = await Topic.findOne({
          userId: req.user.id,
          weekId: task.weekId,
          'subtopics._id': task.subtopicId
        });

        if (topic) {
          const sub = topic.subtopics.id(task.subtopicId);
          if (sub) {
            sub.isCompleted = task.completed;
            sub.actualCompletionDate = task.completed ? new Date() : null;
          }

          // Check overall topic completion
          topic.isCompleted = topic.subtopics.every(s => s.isCompleted);
          topic.actualCompletionDate = topic.isCompleted ? new Date() : null;
          await topic.save();

          // Check week status
          const allTopics = await Topic.find({ userId: req.user.id, weekId: task.weekId });
          const weekDoc = await Week.findById(task.weekId);
          if (weekDoc && allTopics.length > 0) {
            const allDone = allTopics.every(t => t.isCompleted);
            const someDone = allTopics.some(t => t.isCompleted || t.subtopics.some(s => s.isCompleted));
            weekDoc.status = allDone ? 'Completed' : (someDone ? 'In Progress' : 'Not Started');
            weekDoc.actualCompletionDate = allDone ? new Date() : null;
            await weekDoc.save();
          }
        }
      } else if (task.category === 'Aptitude') {
        // Aptitude Tracker Subtopic sync
        const aptTopic = await AptitudeTopic.findOne({
          userId: req.user.id,
          'subtopics._id': task.subtopicId
        });
        if (aptTopic) {
          const sub = aptTopic.subtopics.id(task.subtopicId);
          if (sub) {
            sub.isCompleted = task.completed;
            sub.actualCompletionDate = task.completed ? new Date() : null;
          }
          aptTopic.isCompleted = aptTopic.subtopics.every(s => s.isCompleted);
          aptTopic.actualCompletionDate = aptTopic.isCompleted ? new Date() : null;
          await aptTopic.save();
        }
      }
    }

    // Recompute daily progress percentage
    const dateStr = task.date;
    const tasks = await DailyTask.find({ userId: req.user.id, date: dateStr });
    const progress = await DailyProgress.findOne({ userId: req.user.id, date: dateStr });

    const weights = {
      'Study Hours': 15,
      'DSA': 20,
      'Aptitude': 20,
      'IP Skill': 20,
      'Technical Skill': 15,
      'English Speaking': 10
    };
    let completion = 0;
    tasks.forEach(t => {
      if (t.completed) {
        completion += weights[t.category] || 0;
      }
    });

    if (progress) {
      if (progress.isHoliday) {
        completion = 100;
      }
      progress.completionPercentage = completion;
      await progress.save();
    }

    // Streak logic update
    let streakObj = await Streak.findOne({ userId: req.user.id });
    if (!streakObj) {
      streakObj = await Streak.create({ userId: req.user.id });
    }

    const wasStreakCompleted = streakObj.lastCompletedDate === dateStr;
    const isNowStreakCompleted = completion >= 75; // 75% threshold

    if (isNowStreakCompleted && !wasStreakCompleted) {
      const lastDate = streakObj.lastCompletedDate;
      if (!lastDate) {
        streakObj.currentStreak = 1;
      } else if (isYesterday(lastDate, dateStr)) {
        streakObj.currentStreak += 1;
      } else if (lastDate !== dateStr) {
        streakObj.currentStreak = 1;
      }
      streakObj.longestStreak = Math.max(streakObj.longestStreak, streakObj.currentStreak);
      streakObj.lastCompletedDate = dateStr;
      await streakObj.save();
    } else if (!isNowStreakCompleted && wasStreakCompleted) {
      streakObj.currentStreak = Math.max(0, streakObj.currentStreak - 1);
      streakObj.lastCompletedDate = null;
      await streakObj.save();
    }

    res.status(200).json({
      success: true,
      task,
      tasks,
      progress,
      streak: streakObj
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Toggle attendance status (wentToCollege, isHoliday)
// @route   POST /api/daily/toggle
// @access  Private
exports.toggleChecklistItem = async (req, res, next) => {
  try {
    const { field } = req.body;
    const dateStr = getDateString();

    const allowedFields = ['wentToCollege', 'isHoliday'];
    if (!field || !allowedFields.includes(field)) {
      return res.status(400).json({
        success: false,
        message: 'Invalid attendance field specified'
      });
    }

    const progress = await DailyProgress.findOne({ userId: req.user.id, date: dateStr });
    if (!progress) {
      return res.status(404).json({
        success: false,
        message: 'Daily summary not initialized.'
      });
    }

    progress[field] = !progress[field];
    
    // If holiday is logged, completion becomes 100% bypass
    const tasks = await DailyTask.find({ userId: req.user.id, date: dateStr });
    let completion = 0;
    if (progress.isHoliday) {
      completion = 100;
    } else {
      const weights = {
        'Study Hours': 15,
        'DSA': 20,
        'Aptitude': 20,
        'IP Skill': 20,
        'Technical Skill': 15,
        'English Speaking': 10
      };
      tasks.forEach(t => {
        if (t.completed) {
          completion += weights[t.category] || 0;
        }
      });
    }
    progress.completionPercentage = completion;
    await progress.save();

    // Recheck streak status
    let streakObj = await Streak.findOne({ userId: req.user.id });
    if (streakObj) {
      const wasStreakCompleted = streakObj.lastCompletedDate === dateStr;
      const isNowStreakCompleted = completion >= 75;

      if (isNowStreakCompleted && !wasStreakCompleted) {
        const lastDate = streakObj.lastCompletedDate;
        if (!lastDate) {
          streakObj.currentStreak = 1;
        } else if (isYesterday(lastDate, dateStr)) {
          streakObj.currentStreak += 1;
        } else {
          streakObj.currentStreak = 1;
        }
        streakObj.longestStreak = Math.max(streakObj.longestStreak, streakObj.currentStreak);
        streakObj.lastCompletedDate = dateStr;
        await streakObj.save();
      } else if (!isNowStreakCompleted && wasStreakCompleted) {
        streakObj.currentStreak = Math.max(0, streakObj.currentStreak - 1);
        streakObj.lastCompletedDate = null;
        await streakObj.save();
      }
    }

    res.status(200).json({
      success: true,
      progress,
      tasks,
      streak: streakObj
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get user streak details
// @route   GET /api/daily/streak
// @access  Private
exports.getStreak = async (req, res, next) => {
  try {
    let streakObj = await Streak.findOne({ userId: req.user.id });
    if (!streakObj) {
      streakObj = await Streak.create({ userId: req.user.id });
    }

    const dateStr = getDateString();
    if (streakObj.lastCompletedDate && streakObj.lastCompletedDate !== dateStr && !isYesterday(streakObj.lastCompletedDate, dateStr)) {
      streakObj.currentStreak = 0;
      await streakObj.save();
    }

    res.status(200).json({
      success: true,
      streak: streakObj
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Reset daily streak and completion states
// @route   POST /api/daily/reset
// @access  Private
exports.resetDailyProgress = async (req, res, next) => {
  try {
    const dateStr = getDateString();
    let progress = await DailyProgress.findOne({ userId: req.user.id, date: dateStr });
    if (progress) {
      progress.wentToCollege = false;
      progress.isHoliday = false;
      progress.completionPercentage = 0;
      await progress.save();
    }

    // Reset daily tasks
    await DailyTask.updateMany({ userId: req.user.id, date: dateStr }, { completed: false });
    const tasks = await DailyTask.find({ userId: req.user.id, date: dateStr });

    let streakObj = await Streak.findOne({ userId: req.user.id });
    if (streakObj) {
      streakObj.currentStreak = 0;
      streakObj.longestStreak = 0;
      streakObj.lastCompletedDate = null;
      await streakObj.save();
    }

    res.status(200).json({
      success: true,
      message: 'Completions and streaks successfully reset.',
      progress,
      tasks,
      streak: streakObj
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get daily checklist completions history for last 30 days
// @route   GET /api/daily/history
// @access  Private
exports.getDailyHistory = async (req, res, next) => {
  try {
    const history = await DailyProgress.find({ userId: req.user.id })
      .sort({ date: -1 })
      .limit(30);

    res.status(200).json({
      success: true,
      history: history.reverse().map(item => ({
        date: item.date.slice(5),
        completion: item.completionPercentage
      }))
    });
  } catch (error) {
    next(error);
  }
};
